### ISSUE TITLE
pairwise dissimilarity matrix from clustalo as input for the cc_analysis?

### ISSUE THREAD

**Issue by BinhongLiu** [ksu00/pasimap#1]
Hi, 
Could a pairwise dissimilarity matrix derived from clustalo (http://www.clustal.org/omega/) act as the input for the cc_analysis? I want to analyze the dissimilarity matrix using cc_analysis to get the coordinates.csv file in the Linux server. If so, could you provide a more detailed instrument for preparing of the analysis environment and analyzing steps? I'll be much appreciated it much.

**Comment by ksu00** [comment]
Hey,

thanks for your interest in PaSiMap.

1. Do you want to use PaSiMap with unaligned protein sequences, MSA of protein sequences **OR** pairwise relations?

   **unaligned protein sequences as input:**
   In order to avoid underlying assumptions of a MSA, you can directly use protein sequences as your input for PaSiMap.
   This is the default on the [PaSiMap webserver](http://pasimap.biologie.uni-konstanz.de/).

   **MSA as input:**
   You can use the MSA (e.g. resulting from clustalo) as input for PaSiMap.
   Please see [Help page of PaSiMap webserver](http://pasimap.biologie.uni-konstanz.de/help) for details on how to run this on the webserver.

   **pairwise relations as input:**
   *cc_analysis* requires **similarity** values, so a dissimilarity matrix will not work. Maybe you can convert your dissimilarity values to similarity ones? The possible value range of the similarity values is [-1; 1], with 1 for the perfect similarity (please see [*cc_analysis* paper](https://pubmed.ncbi.nlm.nih.gov/28375141/) for details).
   Please see [Help page of PaSiMap webserver](http://pasimap.biologie.uni-konstanz.de/help) for details on how to run PaSiMap with pairwise relations on the webserver.
   An easier solution would be to simply use your MSA as the input and let PaSiMap internally compute the pairwise similarities for you. 

2. I added a README with instructions on how to set up PaSiMap locally on Linux.

Best wishes

**Comment by BinhongLiu** [comment]
Thanks! This helps me a lot!
